DROP TABLE IF EXISTS `user`;

CREATE TABLE `user`
(
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    username VARCHAR(50) NULL DEFAULT NULL COMMENT '用户名',
    password VARCHAR(100) NULL DEFAULT NULL COMMENT '密码',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

DROP TABLE IF EXISTS `role`;

CREATE TABLE `role`
(
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    role_name VARCHAR(50) NULL DEFAULT NULL COMMENT '角色名称',
    role_code VARCHAR(50) NULL DEFAULT NULL COMMENT '角色编码',
    description VARCHAR(200) NULL DEFAULT NULL COMMENT '角色描述',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

DROP TABLE IF EXISTS `menu`;

CREATE TABLE `menu`
(
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    menu_name VARCHAR(50) NULL DEFAULT NULL COMMENT '菜单名称',
    menu_code VARCHAR(50) NULL DEFAULT NULL COMMENT '菜单编码',
    parent_id VARCHAR(20) NULL DEFAULT '0' COMMENT '父级ID',
    path VARCHAR(100) NULL DEFAULT NULL COMMENT '菜单路径',
    sort INT NULL DEFAULT 0 COMMENT '排序',
    icon VARCHAR(50) NULL DEFAULT NULL COMMENT '图标',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单表';
